### ISSUE TITLE
./convert.sh: line 63: pct: command not found on non-proxmox machine

### ISSUE THREAD

**Issue by Skyridr** [my5t3ry/machine-to-proxmox-lxc-ct-converter#3]
Trying to convert a LCX container from a non-proxmox machine to a proxmox machine, but getting:

./convert.sh: line 63: pct: command not found 

Apparently it can't run this part:

```
pct create $id "/tmp/$name.tar.gz" \
  -description LXC \
  -hostname $name \
  --features nesting=1 \
  -memory $memory -nameserver 8.8.8.8 \
  -net0 name=eth0,ip=$ip/24,gw=$gateway,bridge=$bridge \
  --rootfs $rootsize -storage $storage -password $password
```
  
  Is this supposed to happen?

**Comment by my5t3ry** [comment]
Hi, pct is the tool to manage Linux Containers (LXC) on Proxmox VE. It should be available on your proxmox host if you are root. The default path is '/usr/sbin/pct'. 
Hope that helps : )

**Comment by Skyridr** [comment]
I'm aware of the PCT existence on proxmox :D. But isn't this tool supposed to be run from a non-proxmox server (within a lxc container) so it can transfer it over to a proxmox server?

Original LXC -> Run script inside container -> SSH connection to proxmox server -> Transfer & create proxmox container

**Comment by my5t3ry** [comment]
ok, sorry i misunderstood the problem. You should run the script from on the proxmox server and you need ssh root access to the machine you want to containerize. Use parameter -t to specify the ssh uri of the machine you like to containerize.
