### ISSUE TITLE
PVE 8.0.4 error

### ISSUE THREAD

**Issue by ArMaTeC** [my5t3ry/machine-to-proxmox-lxc-ct-converter#5]
Enter new password: **************
Retype new password: **************
400 Parameter verification failed.
rootfs: invalid format - format error
rootfs.volume: property is missing and it is not optional

memory: type check ('integer') failed - got ''
vmid: type check ('integer') failed - got ''
net0: invalid format - missing key in comma-separated list property

storage: invalid format - storage ID '' contains illegal characters

pct create <vmid> <ostemplate> [OPTIONS]
-bash: -i: command not found

command run:

./convert.sh \
-n NewTestCTConvert \
-t 192.168.1.119 \
-P 22 \ 
-i 109 \
-s 130 \
-a 192.168.1.121 \
-b vmbr0 \
-g 192.168.1.1 \
-m 2048 \
-d default \
-p Somepassword

**Comment by mbachmann-lan** [comment]
I can not confirm this. You may have a typo!?
Converted a Debian 11.7 VM on a Proxmox 8.0.4 Host without problems.

```
./convert.sh \
-n debian11vm \
-t 192.168.50.150 \
-P 22 \
-i 166 \
-s 20 \
-a 192.168.50.199 \
-b vmbr0 \
-g 192.168.50.1 \
-m 1024 \
-d local-lvm \
-p password
```
